### ISSUE TITLE
PDAUG_Sequence_Property_Based_Descriptors

### ISSUE THREAD

**Issue by B0r1sD** [jaidevjoshi83/pdaug#8]
Hi there

The tool PDAUG_Sequence_Property_Based_Descriptors (v0.1.0) doesn't seem to be working on our Galaxy instance. The Python attribute error seems to be pointing towards a problem in the source code itself. 

Toolshed entry: https://toolshed.g2.bx.psu.edu/repository?repository_id=f362d6c54c6e7e0a

Error: 
```shell
Traceback (most recent call last):
  File "/srv/galaxy/shared/database/shed_data/toolshed.g2.bx.psu.edu/repos/jay/pdaug_sequence_property_based_descriptors/9bcde9583f9c/pdaug_sequence_property_based_descriptors/PDAUG_Sequence_Property_Based_Descriptors/PDAUG_Sequence_Property_Based_Descriptors.py", line 170, in <module>
    Decriptor_generator(args.InFile, args.Lamda, args.Weight, args.MaxLag, args.DesType, args.Out_file)
  File "/srv/galaxy/shared/database/shed_data/toolshed.g2.bx.psu.edu/repos/jay/pdaug_sequence_property_based_descriptors/9bcde9583f9c/pdaug_sequence_property_based_descriptors/PDAUG_Sequence_Property_Based_Descriptors/PDAUG_Sequence_Property_Based_Descriptors.py", line 103, in Decriptor_generator
    DS1 = protein.GetAAComp()
  File "/srv/galaxy/shared/etc/dependencies/miniconda3/envs/mulled-v1-1542d31b6bf25d7a9ec7b0474b0e3632971ecd75f4ac7668a650d791af820a0f/lib/python2.7/site-packages/pydpi/pypro.py", line 108, in GetAAComp
    res=CalculateAAComposition(self.ProteinSequence)
AttributeError: PyPro instance has no attribute 'ProteinSequence'
```

Any feedback is appreciated!

**Comment by jaidevjoshi83** [comment]
Hi, Thanks for reporting the issue. I will get back to you soon regarding this.

**Comment by B0r1sD** [comment]
Hey Jay, any update on this perhaps? Seems like the whole PDAUG suite is not working anymore. We will hide the tools for now in our instance.

**Comment by jayadevjoshi** [comment]
> Hey Jay, any update on this perhaps? Seems like the whole PDAUG suite is not working anymore. We will hide the tools for now in our instance.

@B0r1sD Thanks for notifying the issue, I will check this today.

**Comment by B0r1sD** [comment]
Thank you in advance! While looking further into it, it might be our instance not properly finding the [container](https://hub.docker.com/r/jayadevjoshi12/galaxy_pdaug) for other tools part of the PDAUG suite like PDAUG ML Models, not sure yet. So while the original issue is still valid, I'll keep you posted on my previous comment which you can ignore for now. Apologies!

**Comment by jayadevjoshi** [comment]
> Thank you in advance! While looking further into it, it might be our instance not properly finding the [container](https://hub.docker.com/r/jayadevjoshi12/galaxy_pdaug) for other tools part of the PDAUG suite like PDAUG ML Models, not sure yet. So while the original issue is still valid, I'll keep you posted on my previous comment which you can ignore for now. Apologies!

No worries! I have gone through the PDAUG package and most of the tools are working fine. However, I noticed some dependency-related issues with a few tools. When I try to install the tools through the Tool Shed, Galaxy is unable to resolve the dependencies, even though I verified that all the dependencies are available and work correctly when installed manually.  I will try to see if changing the versions of some conflicting dependencies resolves this issue.

**Comment by jayadevjoshi** [comment]
> Hi there
> 
> The tool PDAUG_Sequence_Property_Based_Descriptors (v0.1.0) doesn't seem to be working on our Galaxy instance. The Python attribute error seems to be pointing towards a problem in the source code itself.
> 
> Toolshed entry: https://toolshed.g2.bx.psu.edu/repository?repository_id=f362d6c54c6e7e0a
> 
> Error:
> 
> Traceback (most recent call last):
>   File "/srv/galaxy/shared/database/shed_data/toolshed.g2.bx.psu.edu/repos/jay/pdaug_sequence_property_based_descriptors/9bcde9583f9c/pdaug_sequence_property_based_descriptors/PDAUG_Sequence_Property_Based_Descriptors/PDAUG_Sequence_Property_Based_Descriptors.py", line 170, in <module>
>     Decriptor_generator(args.InFile, args.Lamda, args.Weight, args.MaxLag, args.DesType, args.Out_file)
>   File "/srv/galaxy/shared/database/shed_data/toolshed.g2.bx.psu.edu/repos/jay/pdaug_sequence_property_based_descriptors/9bcde9583f9c/pdaug_sequence_property_based_descriptors/PDAUG_Sequence_Property_Based_Descriptors/PDAUG_Sequence_Property_Based_Descriptors.py", line 103, in Decriptor_generator
>     DS1 = protein.GetAAComp()
>   File "/srv/galaxy/shared/etc/dependencies/miniconda3/envs/mulled-v1-1542d31b6bf25d7a9ec7b0474b0e3632971ecd75f4ac7668a650d791af820a0f/lib/python2.7/site-packages/pydpi/pypro.py", line 108, in GetAAComp
>     res=CalculateAAComposition(self.ProteinSequence)
> AttributeError: PyPro instance has no attribute 'ProteinSequence'
> Any feedback is appreciated!

I’m not able to reproduce this error. The tool is working fine on my instance, even when installed from scratch. However, I will test it thoroughly and get back to you soon.
